// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: facility/facility.proto

package facility

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FacilityServiceClient is the client API for FacilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FacilityServiceClient interface {
	CreateFacility(ctx context.Context, in *FacilityCreateDto, opts ...grpc.CallOption) (*FacilityResponseDto, error)
}

type facilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFacilityServiceClient(cc grpc.ClientConnInterface) FacilityServiceClient {
	return &facilityServiceClient{cc}
}

func (c *facilityServiceClient) CreateFacility(ctx context.Context, in *FacilityCreateDto, opts ...grpc.CallOption) (*FacilityResponseDto, error) {
	out := new(FacilityResponseDto)
	err := c.cc.Invoke(ctx, "/FacilityService/CreateFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacilityServiceServer is the server API for FacilityService service.
// All implementations must embed UnimplementedFacilityServiceServer
// for forward compatibility
type FacilityServiceServer interface {
	CreateFacility(context.Context, *FacilityCreateDto) (*FacilityResponseDto, error)
	mustEmbedUnimplementedFacilityServiceServer()
}

// UnimplementedFacilityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFacilityServiceServer struct {
}

func (UnimplementedFacilityServiceServer) CreateFacility(context.Context, *FacilityCreateDto) (*FacilityResponseDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFacility not implemented")
}
func (UnimplementedFacilityServiceServer) mustEmbedUnimplementedFacilityServiceServer() {}

// UnsafeFacilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FacilityServiceServer will
// result in compilation errors.
type UnsafeFacilityServiceServer interface {
	mustEmbedUnimplementedFacilityServiceServer()
}

func RegisterFacilityServiceServer(s grpc.ServiceRegistrar, srv FacilityServiceServer) {
	s.RegisterService(&FacilityService_ServiceDesc, srv)
}

func _FacilityService_CreateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacilityCreateDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServiceServer).CreateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FacilityService/CreateFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServiceServer).CreateFacility(ctx, req.(*FacilityCreateDto))
	}
	return interceptor(ctx, in, info, handler)
}

// FacilityService_ServiceDesc is the grpc.ServiceDesc for FacilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FacilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FacilityService",
	HandlerType: (*FacilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFacility",
			Handler:    _FacilityService_CreateFacility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "facility/facility.proto",
}
