// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: publicFacilityRequest/publicFacilityRequest.proto

package publicFacilityRequest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicFacilityRequestCreateDtoF_PublicStatus int32

const (
	PublicFacilityRequestCreateDtoF_Pending  PublicFacilityRequestCreateDtoF_PublicStatus = 0
	PublicFacilityRequestCreateDtoF_Accepted PublicFacilityRequestCreateDtoF_PublicStatus = 1
	PublicFacilityRequestCreateDtoF_Rejected PublicFacilityRequestCreateDtoF_PublicStatus = 2
)

// Enum value maps for PublicFacilityRequestCreateDtoF_PublicStatus.
var (
	PublicFacilityRequestCreateDtoF_PublicStatus_name = map[int32]string{
		0: "Pending",
		1: "Accepted",
		2: "Rejected",
	}
	PublicFacilityRequestCreateDtoF_PublicStatus_value = map[string]int32{
		"Pending":  0,
		"Accepted": 1,
		"Rejected": 2,
	}
)

func (x PublicFacilityRequestCreateDtoF_PublicStatus) Enum() *PublicFacilityRequestCreateDtoF_PublicStatus {
	p := new(PublicFacilityRequestCreateDtoF_PublicStatus)
	*p = x
	return p
}

func (x PublicFacilityRequestCreateDtoF_PublicStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicFacilityRequestCreateDtoF_PublicStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[0].Descriptor()
}

func (PublicFacilityRequestCreateDtoF_PublicStatus) Type() protoreflect.EnumType {
	return &file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[0]
}

func (x PublicFacilityRequestCreateDtoF_PublicStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicFacilityRequestCreateDtoF_PublicStatus.Descriptor instead.
func (PublicFacilityRequestCreateDtoF_PublicStatus) EnumDescriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{0, 0}
}

type PublicFacilityRequestResponseDtoF_PublicStatus int32

const (
	PublicFacilityRequestResponseDtoF_Pending  PublicFacilityRequestResponseDtoF_PublicStatus = 0
	PublicFacilityRequestResponseDtoF_Accepted PublicFacilityRequestResponseDtoF_PublicStatus = 1
	PublicFacilityRequestResponseDtoF_Rejected PublicFacilityRequestResponseDtoF_PublicStatus = 2
)

// Enum value maps for PublicFacilityRequestResponseDtoF_PublicStatus.
var (
	PublicFacilityRequestResponseDtoF_PublicStatus_name = map[int32]string{
		0: "Pending",
		1: "Accepted",
		2: "Rejected",
	}
	PublicFacilityRequestResponseDtoF_PublicStatus_value = map[string]int32{
		"Pending":  0,
		"Accepted": 1,
		"Rejected": 2,
	}
)

func (x PublicFacilityRequestResponseDtoF_PublicStatus) Enum() *PublicFacilityRequestResponseDtoF_PublicStatus {
	p := new(PublicFacilityRequestResponseDtoF_PublicStatus)
	*p = x
	return p
}

func (x PublicFacilityRequestResponseDtoF_PublicStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicFacilityRequestResponseDtoF_PublicStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[1].Descriptor()
}

func (PublicFacilityRequestResponseDtoF_PublicStatus) Type() protoreflect.EnumType {
	return &file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[1]
}

func (x PublicFacilityRequestResponseDtoF_PublicStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicFacilityRequestResponseDtoF_PublicStatus.Descriptor instead.
func (PublicFacilityRequestResponseDtoF_PublicStatus) EnumDescriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{1, 0}
}

type PublicFacilityRequestCreateDtoF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64                                        `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AuthorId      int64                                        `protobuf:"varint,2,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	FacilityId    int64                                        `protobuf:"varint,3,opt,name=FacilityId,proto3" json:"FacilityId,omitempty"`
	Status        PublicFacilityRequestCreateDtoF_PublicStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=PublicFacilityRequestCreateDtoF_PublicStatus" json:"Status,omitempty"`
	Created       int64                                        `protobuf:"varint,5,opt,name=Created,proto3" json:"Created,omitempty"`
	AuthorName    string                                       `protobuf:"bytes,6,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	AuthorPicture string                                       `protobuf:"bytes,7,opt,name=AuthorPicture,proto3" json:"AuthorPicture,omitempty"`
}

func (x *PublicFacilityRequestCreateDtoF) Reset() {
	*x = PublicFacilityRequestCreateDtoF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFacilityRequestCreateDtoF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFacilityRequestCreateDtoF) ProtoMessage() {}

func (x *PublicFacilityRequestCreateDtoF) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFacilityRequestCreateDtoF.ProtoReflect.Descriptor instead.
func (*PublicFacilityRequestCreateDtoF) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{0}
}

func (x *PublicFacilityRequestCreateDtoF) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicFacilityRequestCreateDtoF) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PublicFacilityRequestCreateDtoF) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *PublicFacilityRequestCreateDtoF) GetStatus() PublicFacilityRequestCreateDtoF_PublicStatus {
	if x != nil {
		return x.Status
	}
	return PublicFacilityRequestCreateDtoF_Pending
}

func (x *PublicFacilityRequestCreateDtoF) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *PublicFacilityRequestCreateDtoF) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *PublicFacilityRequestCreateDtoF) GetAuthorPicture() string {
	if x != nil {
		return x.AuthorPicture
	}
	return ""
}

type PublicFacilityRequestResponseDtoF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64                                          `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FacilityId   int64                                          `protobuf:"varint,2,opt,name=FacilityId,proto3" json:"FacilityId,omitempty"`
	Status       PublicFacilityRequestResponseDtoF_PublicStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=PublicFacilityRequestResponseDtoF_PublicStatus" json:"Status,omitempty"`
	Comment      string                                         `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Created      int64                                          `protobuf:"varint,5,opt,name=Created,proto3" json:"Created,omitempty"`
	AuthorName   string                                         `protobuf:"bytes,6,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	FacilityName string                                         `protobuf:"bytes,7,opt,name=FacilityName,proto3" json:"FacilityName,omitempty"`
	Author       *UserResponseDtoF                              `protobuf:"bytes,8,opt,name=Author,proto3" json:"Author,omitempty"`
}

func (x *PublicFacilityRequestResponseDtoF) Reset() {
	*x = PublicFacilityRequestResponseDtoF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFacilityRequestResponseDtoF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFacilityRequestResponseDtoF) ProtoMessage() {}

func (x *PublicFacilityRequestResponseDtoF) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFacilityRequestResponseDtoF.ProtoReflect.Descriptor instead.
func (*PublicFacilityRequestResponseDtoF) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{1}
}

func (x *PublicFacilityRequestResponseDtoF) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicFacilityRequestResponseDtoF) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *PublicFacilityRequestResponseDtoF) GetStatus() PublicFacilityRequestResponseDtoF_PublicStatus {
	if x != nil {
		return x.Status
	}
	return PublicFacilityRequestResponseDtoF_Pending
}

func (x *PublicFacilityRequestResponseDtoF) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PublicFacilityRequestResponseDtoF) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *PublicFacilityRequestResponseDtoF) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *PublicFacilityRequestResponseDtoF) GetFacilityName() string {
	if x != nil {
		return x.FacilityName
	}
	return ""
}

func (x *PublicFacilityRequestResponseDtoF) GetAuthor() *UserResponseDtoF {
	if x != nil {
		return x.Author
	}
	return nil
}

type UserResponseDtoF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username       string                `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	ProfilePicture string                `protobuf:"bytes,3,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	Role           int32                 `protobuf:"varint,4,opt,name=Role,proto3" json:"Role,omitempty"`
	IsActive       bool                  `protobuf:"varint,5,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	Followers      []*FollowerCreateDtoF `protobuf:"bytes,6,rep,name=Followers,proto3" json:"Followers,omitempty"`
}

func (x *UserResponseDtoF) Reset() {
	*x = UserResponseDtoF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResponseDtoF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponseDtoF) ProtoMessage() {}

func (x *UserResponseDtoF) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponseDtoF.ProtoReflect.Descriptor instead.
func (*UserResponseDtoF) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponseDtoF) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponseDtoF) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponseDtoF) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *UserResponseDtoF) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserResponseDtoF) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserResponseDtoF) GetFollowers() []*FollowerCreateDtoF {
	if x != nil {
		return x.Followers
	}
	return nil
}

type FollowerCreateDtoF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FollowedById int64 `protobuf:"varint,2,opt,name=FollowedById,proto3" json:"FollowedById,omitempty"`
}

func (x *FollowerCreateDtoF) Reset() {
	*x = FollowerCreateDtoF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowerCreateDtoF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerCreateDtoF) ProtoMessage() {}

func (x *FollowerCreateDtoF) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerCreateDtoF.ProtoReflect.Descriptor instead.
func (*FollowerCreateDtoF) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{3}
}

func (x *FollowerCreateDtoF) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowerCreateDtoF) GetFollowedById() int64 {
	if x != nil {
		return x.FollowedById
	}
	return 0
}

type PublicFacilityRequestListResponseF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicFacilityRequestsResponses []*PublicFacilityRequestResponseDtoF `protobuf:"bytes,1,rep,name=publicFacilityRequestsResponses,proto3" json:"publicFacilityRequestsResponses,omitempty"`
}

func (x *PublicFacilityRequestListResponseF) Reset() {
	*x = PublicFacilityRequestListResponseF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFacilityRequestListResponseF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFacilityRequestListResponseF) ProtoMessage() {}

func (x *PublicFacilityRequestListResponseF) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFacilityRequestListResponseF.ProtoReflect.Descriptor instead.
func (*PublicFacilityRequestListResponseF) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{4}
}

func (x *PublicFacilityRequestListResponseF) GetPublicFacilityRequestsResponses() []*PublicFacilityRequestResponseDtoF {
	if x != nil {
		return x.PublicFacilityRequestsResponses
	}
	return nil
}

type GetRequestParamsF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequestParamsF) Reset() {
	*x = GetRequestParamsF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestParamsF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestParamsF) ProtoMessage() {}

func (x *GetRequestParamsF) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestParamsF.ProtoReflect.Descriptor instead.
func (*GetRequestParamsF) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequestParamsF) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_publicFacilityRequest_publicFacilityRequest_proto protoreflect.FileDescriptor

var file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc = []byte{
	0x0a, 0x31, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61,
	0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xcd, 0x02, 0x0a, 0x1f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x74, 0x6f, 0x46, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x12, 0x45, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2d, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74,
	0x6f, 0x46, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x37, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x02,
	0x22, 0xf8, 0x02, 0x0a, 0x21, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x74, 0x6f, 0x46, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x46, 0x61, 0x63, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46,
	0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x46, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x46, 0x61, 0x63, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x46, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x22, 0x37, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x02, 0x22, 0xc9, 0x01, 0x0a, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x46,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x46, 0x52, 0x09, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x22, 0x50, 0x0a, 0x12, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x46, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x42, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x22, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46,
	0x12, 0x6c, 0x0a, 0x1f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x46, 0x52, 0x1f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x23,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x46, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x32, 0xd7, 0x01, 0x0a, 0x1c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61,
	0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61,
	0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x46, 0x1a,
	0x22, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x74, 0x6f, 0x46, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x23, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46,
	0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x22, 0x00, 0x42, 0x1d, 0x5a,
	0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDescOnce sync.Once
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData = file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc
)

func file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP() []byte {
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDescOnce.Do(func() {
		file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData)
	})
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData
}

var file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_publicFacilityRequest_publicFacilityRequest_proto_goTypes = []interface{}{
	(PublicFacilityRequestCreateDtoF_PublicStatus)(0),   // 0: PublicFacilityRequestCreateDtoF.PublicStatus
	(PublicFacilityRequestResponseDtoF_PublicStatus)(0), // 1: PublicFacilityRequestResponseDtoF.PublicStatus
	(*PublicFacilityRequestCreateDtoF)(nil),             // 2: PublicFacilityRequestCreateDtoF
	(*PublicFacilityRequestResponseDtoF)(nil),           // 3: PublicFacilityRequestResponseDtoF
	(*UserResponseDtoF)(nil),                            // 4: UserResponseDtoF
	(*FollowerCreateDtoF)(nil),                          // 5: FollowerCreateDtoF
	(*PublicFacilityRequestListResponseF)(nil),          // 6: PublicFacilityRequestListResponseF
	(*GetRequestParamsF)(nil),                           // 7: GetRequestParamsF
	(*emptypb.Empty)(nil),                               // 8: google.protobuf.Empty
}
var file_publicFacilityRequest_publicFacilityRequest_proto_depIdxs = []int32{
	0, // 0: PublicFacilityRequestCreateDtoF.Status:type_name -> PublicFacilityRequestCreateDtoF.PublicStatus
	1, // 1: PublicFacilityRequestResponseDtoF.Status:type_name -> PublicFacilityRequestResponseDtoF.PublicStatus
	4, // 2: PublicFacilityRequestResponseDtoF.Author:type_name -> UserResponseDtoF
	5, // 3: UserResponseDtoF.Followers:type_name -> FollowerCreateDtoF
	3, // 4: PublicFacilityRequestListResponseF.publicFacilityRequestsResponses:type_name -> PublicFacilityRequestResponseDtoF
	2, // 5: PublicFacilityRequestService.CreateFacilityRequest:input_type -> PublicFacilityRequestCreateDtoF
	8, // 6: PublicFacilityRequestService.GetAllFacilityRequest:input_type -> google.protobuf.Empty
	3, // 7: PublicFacilityRequestService.CreateFacilityRequest:output_type -> PublicFacilityRequestResponseDtoF
	6, // 8: PublicFacilityRequestService.GetAllFacilityRequest:output_type -> PublicFacilityRequestListResponseF
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_publicFacilityRequest_publicFacilityRequest_proto_init() }
func file_publicFacilityRequest_publicFacilityRequest_proto_init() {
	if File_publicFacilityRequest_publicFacilityRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFacilityRequestCreateDtoF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFacilityRequestResponseDtoF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResponseDtoF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowerCreateDtoF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFacilityRequestListResponseF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestParamsF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publicFacilityRequest_publicFacilityRequest_proto_goTypes,
		DependencyIndexes: file_publicFacilityRequest_publicFacilityRequest_proto_depIdxs,
		EnumInfos:         file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes,
		MessageInfos:      file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes,
	}.Build()
	File_publicFacilityRequest_publicFacilityRequest_proto = out.File
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc = nil
	file_publicFacilityRequest_publicFacilityRequest_proto_goTypes = nil
	file_publicFacilityRequest_publicFacilityRequest_proto_depIdxs = nil
}
