// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: publicFacilityRequest/publicFacilityRequest.proto

package publicFacilityRequest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PublicFacilityRequestServiceClient is the client API for PublicFacilityRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicFacilityRequestServiceClient interface {
	CreateFacilityRequest(ctx context.Context, in *PublicFacilityRequestCreateDtoF, opts ...grpc.CallOption) (*PublicFacilityRequestResponseDtoF, error)
	GetAllFacilityRequest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublicFacilityRequestListResponseF, error)
}

type publicFacilityRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicFacilityRequestServiceClient(cc grpc.ClientConnInterface) PublicFacilityRequestServiceClient {
	return &publicFacilityRequestServiceClient{cc}
}

func (c *publicFacilityRequestServiceClient) CreateFacilityRequest(ctx context.Context, in *PublicFacilityRequestCreateDtoF, opts ...grpc.CallOption) (*PublicFacilityRequestResponseDtoF, error) {
	out := new(PublicFacilityRequestResponseDtoF)
	err := c.cc.Invoke(ctx, "/PublicFacilityRequestService/CreateFacilityRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicFacilityRequestServiceClient) GetAllFacilityRequest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublicFacilityRequestListResponseF, error) {
	out := new(PublicFacilityRequestListResponseF)
	err := c.cc.Invoke(ctx, "/PublicFacilityRequestService/GetAllFacilityRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicFacilityRequestServiceServer is the server API for PublicFacilityRequestService service.
// All implementations must embed UnimplementedPublicFacilityRequestServiceServer
// for forward compatibility
type PublicFacilityRequestServiceServer interface {
	CreateFacilityRequest(context.Context, *PublicFacilityRequestCreateDtoF) (*PublicFacilityRequestResponseDtoF, error)
	GetAllFacilityRequest(context.Context, *emptypb.Empty) (*PublicFacilityRequestListResponseF, error)
	mustEmbedUnimplementedPublicFacilityRequestServiceServer()
}

// UnimplementedPublicFacilityRequestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPublicFacilityRequestServiceServer struct {
}

func (UnimplementedPublicFacilityRequestServiceServer) CreateFacilityRequest(context.Context, *PublicFacilityRequestCreateDtoF) (*PublicFacilityRequestResponseDtoF, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFacilityRequest not implemented")
}
func (UnimplementedPublicFacilityRequestServiceServer) GetAllFacilityRequest(context.Context, *emptypb.Empty) (*PublicFacilityRequestListResponseF, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFacilityRequest not implemented")
}
func (UnimplementedPublicFacilityRequestServiceServer) mustEmbedUnimplementedPublicFacilityRequestServiceServer() {
}

// UnsafePublicFacilityRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicFacilityRequestServiceServer will
// result in compilation errors.
type UnsafePublicFacilityRequestServiceServer interface {
	mustEmbedUnimplementedPublicFacilityRequestServiceServer()
}

func RegisterPublicFacilityRequestServiceServer(s grpc.ServiceRegistrar, srv PublicFacilityRequestServiceServer) {
	s.RegisterService(&PublicFacilityRequestService_ServiceDesc, srv)
}

func _PublicFacilityRequestService_CreateFacilityRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicFacilityRequestCreateDtoF)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicFacilityRequestServiceServer).CreateFacilityRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PublicFacilityRequestService/CreateFacilityRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicFacilityRequestServiceServer).CreateFacilityRequest(ctx, req.(*PublicFacilityRequestCreateDtoF))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicFacilityRequestService_GetAllFacilityRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicFacilityRequestServiceServer).GetAllFacilityRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PublicFacilityRequestService/GetAllFacilityRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicFacilityRequestServiceServer).GetAllFacilityRequest(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicFacilityRequestService_ServiceDesc is the grpc.ServiceDesc for PublicFacilityRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicFacilityRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PublicFacilityRequestService",
	HandlerType: (*PublicFacilityRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFacilityRequest",
			Handler:    _PublicFacilityRequestService_CreateFacilityRequest_Handler,
		},
		{
			MethodName: "GetAllFacilityRequest",
			Handler:    _PublicFacilityRequestService_GetAllFacilityRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publicFacilityRequest/publicFacilityRequest.proto",
}
