// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0--rc2
// source: publicFacilityRequest/publicFacilityRequest.proto

package publicFacilityRequest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicFacilityRequestCreateDto_PublicStatus int32

const (
	PublicFacilityRequestCreateDto_Pending  PublicFacilityRequestCreateDto_PublicStatus = 0
	PublicFacilityRequestCreateDto_Accepted PublicFacilityRequestCreateDto_PublicStatus = 1
	PublicFacilityRequestCreateDto_Rejected PublicFacilityRequestCreateDto_PublicStatus = 2
)

// Enum value maps for PublicFacilityRequestCreateDto_PublicStatus.
var (
	PublicFacilityRequestCreateDto_PublicStatus_name = map[int32]string{
		0: "Pending",
		1: "Accepted",
		2: "Rejected",
	}
	PublicFacilityRequestCreateDto_PublicStatus_value = map[string]int32{
		"Pending":  0,
		"Accepted": 1,
		"Rejected": 2,
	}
)

func (x PublicFacilityRequestCreateDto_PublicStatus) Enum() *PublicFacilityRequestCreateDto_PublicStatus {
	p := new(PublicFacilityRequestCreateDto_PublicStatus)
	*p = x
	return p
}

func (x PublicFacilityRequestCreateDto_PublicStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicFacilityRequestCreateDto_PublicStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[0].Descriptor()
}

func (PublicFacilityRequestCreateDto_PublicStatus) Type() protoreflect.EnumType {
	return &file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[0]
}

func (x PublicFacilityRequestCreateDto_PublicStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicFacilityRequestCreateDto_PublicStatus.Descriptor instead.
func (PublicFacilityRequestCreateDto_PublicStatus) EnumDescriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{0, 0}
}

type PublicFacilityRequestResponseDto_PublicStatus int32

const (
	PublicFacilityRequestResponseDto_Pending  PublicFacilityRequestResponseDto_PublicStatus = 0
	PublicFacilityRequestResponseDto_Accepted PublicFacilityRequestResponseDto_PublicStatus = 1
	PublicFacilityRequestResponseDto_Rejected PublicFacilityRequestResponseDto_PublicStatus = 2
)

// Enum value maps for PublicFacilityRequestResponseDto_PublicStatus.
var (
	PublicFacilityRequestResponseDto_PublicStatus_name = map[int32]string{
		0: "Pending",
		1: "Accepted",
		2: "Rejected",
	}
	PublicFacilityRequestResponseDto_PublicStatus_value = map[string]int32{
		"Pending":  0,
		"Accepted": 1,
		"Rejected": 2,
	}
)

func (x PublicFacilityRequestResponseDto_PublicStatus) Enum() *PublicFacilityRequestResponseDto_PublicStatus {
	p := new(PublicFacilityRequestResponseDto_PublicStatus)
	*p = x
	return p
}

func (x PublicFacilityRequestResponseDto_PublicStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicFacilityRequestResponseDto_PublicStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[1].Descriptor()
}

func (PublicFacilityRequestResponseDto_PublicStatus) Type() protoreflect.EnumType {
	return &file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes[1]
}

func (x PublicFacilityRequestResponseDto_PublicStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicFacilityRequestResponseDto_PublicStatus.Descriptor instead.
func (PublicFacilityRequestResponseDto_PublicStatus) EnumDescriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{1, 0}
}

type PublicFacilityRequestCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64                                       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AuthorId      int64                                       `protobuf:"varint,2,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	FacilityId    int64                                       `protobuf:"varint,3,opt,name=FacilityId,proto3" json:"FacilityId,omitempty"`
	Status        PublicFacilityRequestCreateDto_PublicStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=PublicFacilityRequestCreateDto_PublicStatus" json:"Status,omitempty"`
	Created       int64                                       `protobuf:"varint,5,opt,name=Created,proto3" json:"Created,omitempty"`
	AuthorName    string                                      `protobuf:"bytes,6,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	AuthorPicture string                                      `protobuf:"bytes,7,opt,name=AuthorPicture,proto3" json:"AuthorPicture,omitempty"`
}

func (x *PublicFacilityRequestCreateDto) Reset() {
	*x = PublicFacilityRequestCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFacilityRequestCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFacilityRequestCreateDto) ProtoMessage() {}

func (x *PublicFacilityRequestCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFacilityRequestCreateDto.ProtoReflect.Descriptor instead.
func (*PublicFacilityRequestCreateDto) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{0}
}

func (x *PublicFacilityRequestCreateDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicFacilityRequestCreateDto) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PublicFacilityRequestCreateDto) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *PublicFacilityRequestCreateDto) GetStatus() PublicFacilityRequestCreateDto_PublicStatus {
	if x != nil {
		return x.Status
	}
	return PublicFacilityRequestCreateDto_Pending
}

func (x *PublicFacilityRequestCreateDto) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *PublicFacilityRequestCreateDto) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *PublicFacilityRequestCreateDto) GetAuthorPicture() string {
	if x != nil {
		return x.AuthorPicture
	}
	return ""
}

type PublicFacilityRequestResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64                                         `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FacilityId   int64                                         `protobuf:"varint,2,opt,name=FacilityId,proto3" json:"FacilityId,omitempty"`
	Status       PublicFacilityRequestResponseDto_PublicStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=PublicFacilityRequestResponseDto_PublicStatus" json:"Status,omitempty"`
	Comment      string                                        `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Created      int64                                         `protobuf:"varint,5,opt,name=Created,proto3" json:"Created,omitempty"`
	AuthorName   string                                        `protobuf:"bytes,6,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	FacilityName string                                        `protobuf:"bytes,7,opt,name=FacilityName,proto3" json:"FacilityName,omitempty"`
	Author       *UserResponseDto                              `protobuf:"bytes,8,opt,name=Author,proto3" json:"Author,omitempty"`
}

func (x *PublicFacilityRequestResponseDto) Reset() {
	*x = PublicFacilityRequestResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFacilityRequestResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFacilityRequestResponseDto) ProtoMessage() {}

func (x *PublicFacilityRequestResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFacilityRequestResponseDto.ProtoReflect.Descriptor instead.
func (*PublicFacilityRequestResponseDto) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{1}
}

func (x *PublicFacilityRequestResponseDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicFacilityRequestResponseDto) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *PublicFacilityRequestResponseDto) GetStatus() PublicFacilityRequestResponseDto_PublicStatus {
	if x != nil {
		return x.Status
	}
	return PublicFacilityRequestResponseDto_Pending
}

func (x *PublicFacilityRequestResponseDto) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PublicFacilityRequestResponseDto) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *PublicFacilityRequestResponseDto) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *PublicFacilityRequestResponseDto) GetFacilityName() string {
	if x != nil {
		return x.FacilityName
	}
	return ""
}

func (x *PublicFacilityRequestResponseDto) GetAuthor() *UserResponseDto {
	if x != nil {
		return x.Author
	}
	return nil
}

type UserResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username       string               `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	ProfilePicture string               `protobuf:"bytes,3,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	Role           int32                `protobuf:"varint,4,opt,name=Role,proto3" json:"Role,omitempty"`
	IsActive       bool                 `protobuf:"varint,5,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	Followers      []*FollowerCreateDto `protobuf:"bytes,6,rep,name=Followers,proto3" json:"Followers,omitempty"`
}

func (x *UserResponseDto) Reset() {
	*x = UserResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponseDto) ProtoMessage() {}

func (x *UserResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponseDto.ProtoReflect.Descriptor instead.
func (*UserResponseDto) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponseDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponseDto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponseDto) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *UserResponseDto) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserResponseDto) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserResponseDto) GetFollowers() []*FollowerCreateDto {
	if x != nil {
		return x.Followers
	}
	return nil
}

type FollowerCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FollowedById int64 `protobuf:"varint,2,opt,name=FollowedById,proto3" json:"FollowedById,omitempty"`
}

func (x *FollowerCreateDto) Reset() {
	*x = FollowerCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowerCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerCreateDto) ProtoMessage() {}

func (x *FollowerCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerCreateDto.ProtoReflect.Descriptor instead.
func (*FollowerCreateDto) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{3}
}

func (x *FollowerCreateDto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowerCreateDto) GetFollowedById() int64 {
	if x != nil {
		return x.FollowedById
	}
	return 0
}

type PublicFacilityRequestListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicFacilityRequestsResponses []*PublicFacilityRequestResponseDto `protobuf:"bytes,1,rep,name=publicFacilityRequestsResponses,proto3" json:"publicFacilityRequestsResponses,omitempty"`
}

func (x *PublicFacilityRequestListResponse) Reset() {
	*x = PublicFacilityRequestListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFacilityRequestListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFacilityRequestListResponse) ProtoMessage() {}

func (x *PublicFacilityRequestListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFacilityRequestListResponse.ProtoReflect.Descriptor instead.
func (*PublicFacilityRequestListResponse) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{4}
}

func (x *PublicFacilityRequestListResponse) GetPublicFacilityRequestsResponses() []*PublicFacilityRequestResponseDto {
	if x != nil {
		return x.PublicFacilityRequestsResponses
	}
	return nil
}

type GetRequestParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequestParams) Reset() {
	*x = GetRequestParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestParams) ProtoMessage() {}

func (x *GetRequestParams) ProtoReflect() protoreflect.Message {
	mi := &file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestParams.ProtoReflect.Descriptor instead.
func (*GetRequestParams) Descriptor() ([]byte, []int) {
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequestParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_publicFacilityRequest_publicFacilityRequest_proto protoreflect.FileDescriptor

var file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc = []byte{
	0x0a, 0x31, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61,
	0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x02, 0x0a, 0x1e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61,
	0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x37, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10,
	0x02, 0x22, 0xf5, 0x02, 0x0a, 0x20, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x46, 0x61, 0x63, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46,
	0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x22, 0x37, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x02, 0x22, 0xc7, 0x01, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x30, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x22, 0x4f, 0x0a, 0x11, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64,
	0x42, 0x79, 0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x21, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46,
	0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x1f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x1f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61,
	0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x6e, 0x0a, 0x1c, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61,
	0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x21, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46,
	0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x61, 0x63, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDescOnce sync.Once
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData = file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc
)

func file_publicFacilityRequest_publicFacilityRequest_proto_rawDescGZIP() []byte {
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDescOnce.Do(func() {
		file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData)
	})
	return file_publicFacilityRequest_publicFacilityRequest_proto_rawDescData
}

var file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_publicFacilityRequest_publicFacilityRequest_proto_goTypes = []interface{}{
	(PublicFacilityRequestCreateDto_PublicStatus)(0),   // 0: PublicFacilityRequestCreateDto.PublicStatus
	(PublicFacilityRequestResponseDto_PublicStatus)(0), // 1: PublicFacilityRequestResponseDto.PublicStatus
	(*PublicFacilityRequestCreateDto)(nil),             // 2: PublicFacilityRequestCreateDto
	(*PublicFacilityRequestResponseDto)(nil),           // 3: PublicFacilityRequestResponseDto
	(*UserResponseDto)(nil),                            // 4: UserResponseDto
	(*FollowerCreateDto)(nil),                          // 5: FollowerCreateDto
	(*PublicFacilityRequestListResponse)(nil),          // 6: PublicFacilityRequestListResponse
	(*GetRequestParams)(nil),                           // 7: GetRequestParams
}
var file_publicFacilityRequest_publicFacilityRequest_proto_depIdxs = []int32{
	0, // 0: PublicFacilityRequestCreateDto.Status:type_name -> PublicFacilityRequestCreateDto.PublicStatus
	1, // 1: PublicFacilityRequestResponseDto.Status:type_name -> PublicFacilityRequestResponseDto.PublicStatus
	4, // 2: PublicFacilityRequestResponseDto.Author:type_name -> UserResponseDto
	5, // 3: UserResponseDto.Followers:type_name -> FollowerCreateDto
	3, // 4: PublicFacilityRequestListResponse.publicFacilityRequestsResponses:type_name -> PublicFacilityRequestResponseDto
	2, // 5: PublicFacilityRequestService.Create:input_type -> PublicFacilityRequestCreateDto
	3, // 6: PublicFacilityRequestService.Create:output_type -> PublicFacilityRequestResponseDto
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_publicFacilityRequest_publicFacilityRequest_proto_init() }
func file_publicFacilityRequest_publicFacilityRequest_proto_init() {
	if File_publicFacilityRequest_publicFacilityRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFacilityRequestCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFacilityRequestResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowerCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFacilityRequestListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publicFacilityRequest_publicFacilityRequest_proto_goTypes,
		DependencyIndexes: file_publicFacilityRequest_publicFacilityRequest_proto_depIdxs,
		EnumInfos:         file_publicFacilityRequest_publicFacilityRequest_proto_enumTypes,
		MessageInfos:      file_publicFacilityRequest_publicFacilityRequest_proto_msgTypes,
	}.Build()
	File_publicFacilityRequest_publicFacilityRequest_proto = out.File
	file_publicFacilityRequest_publicFacilityRequest_proto_rawDesc = nil
	file_publicFacilityRequest_publicFacilityRequest_proto_goTypes = nil
	file_publicFacilityRequest_publicFacilityRequest_proto_depIdxs = nil
}
