// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0--rc2
// source: equipment/equipment.proto

package equipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EquipmentCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *EquipmentCreateDto) Reset() {
	*x = EquipmentCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_equipment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentCreateDto) ProtoMessage() {}

func (x *EquipmentCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_equipment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentCreateDto.ProtoReflect.Descriptor instead.
func (*EquipmentCreateDto) Descriptor() ([]byte, []int) {
	return file_equipment_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *EquipmentCreateDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EquipmentCreateDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type EquipmentResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *EquipmentResponseDto) Reset() {
	*x = EquipmentResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_equipment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentResponseDto) ProtoMessage() {}

func (x *EquipmentResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_equipment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentResponseDto.ProtoReflect.Descriptor instead.
func (*EquipmentResponseDto) Descriptor() ([]byte, []int) {
	return file_equipment_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *EquipmentResponseDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentResponseDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EquipmentResponseDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type EquipmentListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipmentResponses []*EquipmentResponseDto `protobuf:"bytes,1,rep,name=equipmentResponses,proto3" json:"equipmentResponses,omitempty"`
}

func (x *EquipmentListResponse) Reset() {
	*x = EquipmentListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_equipment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentListResponse) ProtoMessage() {}

func (x *EquipmentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_equipment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentListResponse.ProtoReflect.Descriptor instead.
func (*EquipmentListResponse) Descriptor() ([]byte, []int) {
	return file_equipment_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *EquipmentListResponse) GetEquipmentResponses() []*EquipmentResponseDto {
	if x != nil {
		return x.EquipmentResponses
	}
	return nil
}

type GetEquipmentParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEquipmentParams) Reset() {
	*x = GetEquipmentParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_equipment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEquipmentParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipmentParams) ProtoMessage() {}

func (x *GetEquipmentParams) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_equipment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipmentParams.ProtoReflect.Descriptor instead.
func (*GetEquipmentParams) Descriptor() ([]byte, []int) {
	return file_equipment_equipment_proto_rawDescGZIP(), []int{3}
}

func (x *GetEquipmentParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_equipment_equipment_proto protoreflect.FileDescriptor

var file_equipment_equipment_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x12, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x14, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x5e, 0x0a, 0x15, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x12, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x12,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x8f, 0x01, 0x0a, 0x10, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x13, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x15, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_equipment_equipment_proto_rawDescOnce sync.Once
	file_equipment_equipment_proto_rawDescData = file_equipment_equipment_proto_rawDesc
)

func file_equipment_equipment_proto_rawDescGZIP() []byte {
	file_equipment_equipment_proto_rawDescOnce.Do(func() {
		file_equipment_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(file_equipment_equipment_proto_rawDescData)
	})
	return file_equipment_equipment_proto_rawDescData
}

var file_equipment_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_equipment_equipment_proto_goTypes = []interface{}{
	(*EquipmentCreateDto)(nil),    // 0: EquipmentCreateDto
	(*EquipmentResponseDto)(nil),  // 1: EquipmentResponseDto
	(*EquipmentListResponse)(nil), // 2: EquipmentListResponse
	(*GetEquipmentParams)(nil),    // 3: GetEquipmentParams
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_equipment_equipment_proto_depIdxs = []int32{
	1, // 0: EquipmentListResponse.equipmentResponses:type_name -> EquipmentResponseDto
	0, // 1: EquipmentService.CreateEquipment:input_type -> EquipmentCreateDto
	4, // 2: EquipmentService.GetAll:input_type -> google.protobuf.Empty
	1, // 3: EquipmentService.CreateEquipment:output_type -> EquipmentResponseDto
	2, // 4: EquipmentService.GetAll:output_type -> EquipmentListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_equipment_equipment_proto_init() }
func file_equipment_equipment_proto_init() {
	if File_equipment_equipment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_equipment_equipment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_equipment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_equipment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_equipment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEquipmentParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_equipment_equipment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_equipment_equipment_proto_goTypes,
		DependencyIndexes: file_equipment_equipment_proto_depIdxs,
		MessageInfos:      file_equipment_equipment_proto_msgTypes,
	}.Build()
	File_equipment_equipment_proto = out.File
	file_equipment_equipment_proto_rawDesc = nil
	file_equipment_equipment_proto_goTypes = nil
	file_equipment_equipment_proto_depIdxs = nil
}
